from python:3.13.9-slim-bookworm

WORKDIR /app
ENV PYTHONUNBUFFERED=1
COPY requirements.txt /app
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
# CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8036", "--log-config", "app/logging.yaml"]
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8036"]